In [1]:
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor

In [2]:
# Download training data from open datasets.
path = "/home/mint-lab/cjh_ws/ThinkAutonomous"
training_data = datasets.FashionMNIST(
    root=".",
    train=True,
    download=False,
    transform=ToTensor(),
)

# Download test data from open datasets.
test_data = datasets.FashionMNIST(
    root=".",
    train=False,
    download=False,
    transform=ToTensor(),
)

In [4]:
print(test_data[0][0].shape)

torch.Size([1, 28, 28])


In [3]:
NUM_WORKERS = 1 
TEST_BATCH_SIZE  = 64
TRAIN_BATCH_SIZE = 16
VALID_SIZE = 0.2

train_dataloader = DataLoader(training_data, batch_size=TRAIN_BATCH_SIZE)
test_dataloader = DataLoader(test_data, batch_size=TEST_BATCH_SIZE)

for X, y in test_dataloader:
    print(f"Shape of X [N, C, H, W]: {X.shape}")
    print(f"Shape of y: {y.shape} {y.dtype}")
    break

Shape of X [N, C, H, W]: torch.Size([64, 1, 28, 28])
Shape of y: torch.Size([64]) torch.int64


In [10]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using {device} device")

class LinearNeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512, 256),
            nn.ReLU(),
            nn.Linear(256, 128),
            nn.ReLU(),
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Linear(64, 32),
            nn.ReLU(),
            nn.Linear(32, 10)
        )

    def forward(self, x):
        x = self.flatten(x)
        logits = self.linear_relu_stack(x)
        return logits

class ConvNueralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(1, 28, kernel_size=3, stride=1)
        self.conv2 = nn.Conv2d(28, 14, kernel_size=3, stride=1)
        self.conv3 = nn.Conv2d(10, 10, kernel_size=3, stride=1)
        self.flatten = nn.Flatten()
        self.linear = nn.Linear(100, 10)
    
    def forward(self, x):
        x = nn.ReLU(self.con1(x))
        x = nn.ReLU(self.con2(x))
        x = nn.ReLU(self.con3(x))
        x = self.flatten(x)
        x = self.linear(x)
        return x

linear_model = LinearNeuralNetwork().to(device)
conv_model = ConvNueralNetwork().to(device)

Using cuda device


In [12]:
conv2d = nn.Conv2d(1, 28, kernel_size=3, stride=1)
input_image = torch.rand(1, 28, 28)

In [13]:
print(conv2d(input_image))

RuntimeError: Expected 4-dimensional input for 4-dimensional weight [28, 1, 3, 3], but got 3-dimensional input of size [1, 28, 28] instead

In [24]:
x = torch.rand(10)

In [25]:
x

tensor([0.6797, 0.7743, 0.4189, 0.0660, 0.5070, 0.6278, 0.3472, 0.4449, 0.4058,
        0.7808])

In [26]:
x.view(-1, 10)

tensor([[0.6797, 0.7743, 0.4189, 0.0660, 0.5070, 0.6278, 0.3472, 0.4449, 0.4058,
         0.7808]])

In [23]:
y

tensor([[0.3751, 0.9232, 0.9659, 0.4996, 0.3391, 0.7702, 0.0654, 0.0862, 0.7560,
         0.7869]])

In [28]:
help(torch.Tensor().view)

Help on built-in function view:

view(...) method of torch.Tensor instance
    view(*shape) -> Tensor
    
    Returns a new tensor with the same data as the :attr:`self` tensor but of a
    different :attr:`shape`.
    
    The returned tensor shares the same data and must have the same number
    of elements, but may have a different size. For a tensor to be viewed, the new
    view size must be compatible with its original size and stride, i.e., each new
    view dimension must either be a subspace of an original dimension, or only span
    across original dimensions :math:`d, d+1, \dots, d+k` that satisfy the following
    contiguity-like condition that :math:`\forall i = d, \dots, d+k-1`,
    
    .. math::
    
      \text{stride}[i] = \text{stride}[i+1] \times \text{size}[i+1]
    
    Otherwise, it will not be possible to view :attr:`self` tensor as :attr:`shape`
    without copying it (e.g., via :meth:`contiguous`). When it is unclear whether a
    :meth:`view` can be performe

In [ ]:
torch.Tensor().view

In [ ]:
!tensorboard --logdir=runs

2022-04-27 21:34:25.505960: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-27 21:34:25.511434: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-04-27 21:34:25.512048: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
[2022-04-27T12:34:25Z ERROR rustboard_core::disk_logdir] While walking log directory: IO error for operation on runs: No such file or directory (os error 2)

NOTE: Using experimental fast data loading logic. To disable, pass
    "--load_fast=false" and report issues on GitHub. More details:
    https://github.com/tensorflow/tensorboard/is